### ISSUE TITLE
Can you provide a working example?

### ISSUE THREAD

**Issue by Maximize0987** [Supereg/homebridge-http-notification-server#1]
I have been using your http-switch on my first device it is installed into a viper car alarm/starter remote.
I used a esp-01 and I coded it to start motor, stop motor, lock, and unlock doors with a web server.  Then I used your http-switch and I can now control it with Siri (very happy).  I am now working on my second device it will be another esp device with more functions.  I am very new to coding, so I was hoping you could provide an entire sketch from a working device with multiple requests that way I can see how it is all put together.  Too many left open placeholders, confuses me because I cannot see where that placeholder is set/changed in the sketch.  Hoping I am not asking too much, but Thanks.

**Comment by bauer-andreas** [comment]
This would of course be possible. However this probably takes me about an week to get my head behind.
I would probably write the example in nodejs. Would that fit your needs?

**Comment by Maximize0987** [comment]
sorry I assumed you would have some written to personal devices, that would show me how it is put together as a whole.  I think I should keep looking at other HTTP-requests, as they are similar, to come to an understanding of what i need to change to my own Strings.  Thanks

**Comment by bauer-andreas** [comment]
Of course I have some own code running. However that is structured a bit more complex and written in Java. I don't really know if that is really helpful.
What is your problem currently? What do you want to achieve? I didn't really get why you would need the notification-server component?

**Comment by Maximize0987** [comment]
ok so a car that you unlock like my with esp8266 and http-switch, then you have a esp8266 in the car that says door status is unlocked when requested by http.  then lets complicate it with multiple.  what is the cars interior temp? what is the cars battery voltage?  What is the cars running status?

**Comment by vbuyakov** [comment]
Feel free to use my esp8266 project 
https://github.com/vbuyakov/espMultiChannelSwitcher .
It uses HTTP-SWITCH and Notify Server.
