### ISSUE TITLE
repeat url multiple times

### ISSUE THREAD

**Issue by Maximize0987** [Supereg/homebridge-http-notification-server#3]
Is there a way to have a url repeat with a short delay between

here is my idea (which I know doesn't work) its for an ir send where you want to go up/down several increments like volume or temperature. 

 - my example idea - 
        {  
            "accessory": "HTTP-SWITCH",
            "name": "Volume Up Five",
            "switchType": "stateless",
            "onUrl": "http://172.22.136.102/ir?code=551502015",
            delay(250),
            "onUrl": "http://172.22.136.102/ir?code=551502015",
            delay(250),
            "onUrl": "http://172.22.136.102/ir?code=551502015",
            delay(250),
            "onUrl": "http://172.22.136.102/ir?code=551502015",
            delay(250),
            "onUrl": "http://172.22.136.102/ir?code=551502015"
        }

**Comment by bauer-andreas** [comment]
You probably meant to post this issue at the "homebridge-http-switch" repository.

It is currently not possible, however I already though about ways to implement this one.
I read back if I have a solution for this problem.

**Comment by bauer-andreas** [comment]
Okay v0.5.9 of `homebridge-http-switch` implements the ability to specify a delay between the executed urls.
Requirement is to set the `multipleUrlExecutionStrategy` property to "series".  
Then have a look at the [delay urls](https://github.com/Supereg/homebridge-http-switch#the-delay-url) in the README.
