### ISSUE TITLE
New client of notification-server

### ISSUE THREAD

**Issue by QuickSander** [Supereg/homebridge-http-notification-server#5]
A shameless copy of your temperature sensor modified to function as an ambient light sensor:

https://github.com/QuickSander/homebridge-http-ambient-light-sensor

**Comment by bauer-andreas** [comment]
Please notice that you infringed my supplied ISC license by removing my copyright notice (as stated in the license: `...provided that the above copyright notice and this permission notice appear in all copies.`).
Please correct that and I would love to add your project to the list ✌🏽

**Comment by QuickSander** [comment]
Appologies for the blunt search/replace. I have corrected it now by noting you as the original author so the copyright notice is still there as per ISC license.
